apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-pulse

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - brain-volume.yaml
  - configmap.yaml
  - api-deployment.yaml
  - workers.yaml
  - ingress.yaml

images:
  - name: project-pulse-api
    newTag: latest
